{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/rsher60/LLM_Codebase/blob/main/items.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# imports\n",
        "\n",
        "import os\n",
        "import random\n",
        "from dotenv import load_dotenv\n",
        "from huggingface_hub import login\n",
        "from datasets import load_dataset, Dataset, DatasetDict\n",
        "\n",
        "from items import Item\n",
        "\n",
        "import matplotlib.pyplot as plt\n",
        "from collections import Counter, defaultdict\n",
        "import numpy as np\n",
        "import pickle"
      ],
      "metadata": {
        "id": "CGcQC6_mOOa6"
      },
      "execution_count": 5,
      "outputs": []
    },
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "YeUwV8w82AAD",
        "outputId": "786e815c-53c8-4c33-94fc-56030535be70"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "\u001b[?25l     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m0.0/78.6 kB\u001b[0m \u001b[31m?\u001b[0m eta \u001b[36m-:--:--\u001b[0m\r\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m78.6/78.6 kB\u001b[0m \u001b[31m2.1 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m480.6/480.6 kB\u001b[0m \u001b[31m10.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m116.3/116.3 kB\u001b[0m \u001b[31m10.8 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m179.3/179.3 kB\u001b[0m \u001b[31m17.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m134.8/134.8 kB\u001b[0m \u001b[31m13.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m194.1/194.1 kB\u001b[0m \u001b[31m16.2 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25h  Building wheel for typing (setup.py) ... \u001b[?25l\u001b[?25hdone\n",
            "\u001b[31mERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.\n",
            "gcsfs 2024.10.0 requires fsspec==2024.10.0, but you have fsspec 2024.9.0 which is incompatible.\u001b[0m\u001b[31m\n",
            "\u001b[0m"
          ]
        }
      ],
      "source": [
        "!pip install -q typing transformers datasets python_dotenv"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 6,
      "metadata": {
        "id": "f84s2AJ_1yNZ"
      },
      "outputs": [],
      "source": [
        "from typing import Optional\n",
        "from transformers import AutoTokenizer\n",
        "import re\n",
        "from datasets import load_dataset"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 62,
      "metadata": {
        "id": "w6kp1q-a24t3"
      },
      "outputs": [],
      "source": [
        "data = load_dataset(\"pgurazada1/amazon_india_products\")[\"train\"]"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Investigate a particular datapoint\n",
        "datapoint = data[2]"
      ],
      "metadata": {
        "id": "IZJRokjoF6bM"
      },
      "execution_count": 63,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "datapoint"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "3uxsTrzlHx2j",
        "outputId": "7ac37503-2209-4764-d6c2-ac566cffbc90"
      },
      "execution_count": 64,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "{'Uniq Id': '41654633cce38c8650690f6dbac01fd3',\n",
              " 'Crawl Timestamp': '2019-10-30 09:53:23 +0000',\n",
              " 'Category': 'Skin Care',\n",
              " 'Product Title': ' Generic 1 Pc brand snail eye cream remove dark circle eye lifting instant ageless snail cream for eye care anti wrinkle eyes cream 20g ',\n",
              " 'Product Description': 'Use: eye, item type: cream, net wt: 20g, gzzz: ygzwbz, model number: lkwnys, gender: female, certification: gzzz, feature: moisturizing, dark circle, anti-puffiness, anti-aging, brand name: laikou, certificate number: 2014028630, ingredient: cream, country/region of manufacture: china, eye care features: eye cream, product name: snail extract cream, applicable to the crowd: general, specifications: normal specifications, origin: shantou, guangdong province, unit type: piece, package weight: ,package size:',\n",
              " 'Brand': 'Generic',\n",
              " 'Pack Size Or Quantity': None,\n",
              " 'Mrp': '1824.00',\n",
              " 'Price': '1042.00',\n",
              " 'Site Name': 'Amazon In',\n",
              " 'Offers': '42.87%',\n",
              " 'Combo Offers': None,\n",
              " 'Stock Availibility': 'YES',\n",
              " 'Product Asin': 'B07DCSN8MP',\n",
              " 'Image Urls': 'https://images-na.ssl-images-amazon.com/images/I/51bWWBIkeZL._AC_US40_.jpg|https://images-na.ssl-images-amazon.com/images/I/51bWWBIkeZL._AC_US40_.jpg|https://images-na.ssl-images-amazon.com/images/I/51FWHBskhHL._AC_US40_.jpg|https://images-na.ssl-images-amazon.com/images/I/51uynr8t2tL._AC_US40_.jpg|https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/transparent-pixel._V192234675_.gif'}"
            ]
          },
          "metadata": {},
          "execution_count": 64
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# How many have prices?\n",
        "\n",
        "prices = 0\n",
        "for datapoint in data:\n",
        "    try:\n",
        "        price = float(datapoint[\"Mrp\"] or 0.0)\n",
        "        if price > 0.0:\n",
        "            prices += 1\n",
        "    except ValueError as e:\n",
        "        pass\n",
        "\n",
        "print(f\"There are {prices:,} with prices which is {prices/len(data)*100:,.1f}%\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "jcyuPWDwH5xU",
        "outputId": "04c98581-8afd-4b54-9c1e-695012012f0b"
      },
      "execution_count": 65,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "There are 29,240 with prices which is 97.5%\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 78,
      "metadata": {
        "id": "2wMZFrlV3CHB"
      },
      "outputs": [],
      "source": [
        "import pandas as pd\n",
        "df  = pd.DataFrame(data)"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#Drop the rows where the price is none and then delete rows where price is 0.0\n",
        "\n",
        "df = df.dropna(subset=['Mrp'])\n",
        "\n"
      ],
      "metadata": {
        "id": "z0AuixCWJAzY"
      },
      "execution_count": 79,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "df.dtypes"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 554
        },
        "id": "lStHDuBNflj8",
        "outputId": "f86c7e8b-4e36-41cf-b048-484fef8ef498"
      },
      "execution_count": 80,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "Uniq Id                  object\n",
              "Crawl Timestamp          object\n",
              "Category                 object\n",
              "Product Title            object\n",
              "Product Description      object\n",
              "Brand                    object\n",
              "Pack Size Or Quantity    object\n",
              "Mrp                      object\n",
              "Price                    object\n",
              "Site Name                object\n",
              "Offers                   object\n",
              "Combo Offers             object\n",
              "Stock Availibility       object\n",
              "Product Asin             object\n",
              "Image Urls               object\n",
              "dtype: object"
            ],
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>0</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>Uniq Id</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Crawl Timestamp</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Category</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Product Title</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Product Description</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Brand</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Pack Size Or Quantity</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Mrp</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Price</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Site Name</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Offers</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Combo Offers</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Stock Availibility</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Product Asin</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Image Urls</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div><br><label><b>dtype:</b> object</label>"
            ]
          },
          "metadata": {},
          "execution_count": 80
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "clean_price('2.4.00')"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 35
        },
        "id": "ozkDPEedfpvC",
        "outputId": "f675db9f-3fbd-4690-e678-468163dcb4b5"
      },
      "execution_count": 84,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "'24.00'"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "string"
            }
          },
          "metadata": {},
          "execution_count": 84
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# CHange the data tyoe of the column to float\n",
        "\n",
        "import re\n",
        "\n",
        "def clean_price(price_str):\n",
        "  \"\"\"Cleans a price string by removing extra decimal points.\"\"\"\n",
        "  if price_str.count('.') ==2:\n",
        "    cleaned_price = re.sub(r\"\\.\", \"\", price_str.strip(), count=1)\n",
        "    return cleaned_price\n",
        "  else:\n",
        "    return price_str\n"
      ],
      "metadata": {
        "id": "v1fIJtKMd6ko"
      },
      "execution_count": 85,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# added code to colab"
      ],
      "metadata": {
        "id": "HKlvqNsyh-ra"
      },
      "execution_count": null,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# apply the clean price function\n",
        "\n",
        "df['Mrp'] = df['Mrp'].apply(lambda x : float(clean_price(x) or 0.0))\n"
      ],
      "metadata": {
        "id": "uENzmHQxgpRI"
      },
      "execution_count": 86,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "df.dtypes"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 554
        },
        "id": "zSzbUdSXg3UT",
        "outputId": "630a7bd3-6791-4e6d-eb2f-d8a80608db48"
      },
      "execution_count": 89,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "Uniq Id                   object\n",
              "Crawl Timestamp           object\n",
              "Category                  object\n",
              "Product Title             object\n",
              "Product Description       object\n",
              "Brand                     object\n",
              "Pack Size Or Quantity     object\n",
              "Mrp                      float64\n",
              "Price                     object\n",
              "Site Name                 object\n",
              "Offers                    object\n",
              "Combo Offers              object\n",
              "Stock Availibility        object\n",
              "Product Asin              object\n",
              "Image Urls                object\n",
              "dtype: object"
            ],
            "text/html": [
              "<div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>0</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>Uniq Id</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Crawl Timestamp</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Category</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Product Title</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Product Description</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Brand</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Pack Size Or Quantity</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Mrp</th>\n",
              "      <td>float64</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Price</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Site Name</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Offers</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Combo Offers</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Stock Availibility</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Product Asin</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>Image Urls</th>\n",
              "      <td>object</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div><br><label><b>dtype:</b> object</label>"
            ]
          },
          "metadata": {},
          "execution_count": 89
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "df.head(10)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "id": "7mhgCvG6e_vU",
        "outputId": "3d122312-9acc-42d1-cff8-a920f5050b4c"
      },
      "execution_count": 93,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "                            Uniq Id            Crawl Timestamp  \\\n",
              "0  eb49cc038190f6f03c272f79fbbce894  2019-10-30 11:38:11 +0000   \n",
              "1  1657cc30c438affede6a5060d6847363  2019-10-31 15:46:54 +0000   \n",
              "2  41654633cce38c8650690f6dbac01fd3  2019-10-30 09:53:23 +0000   \n",
              "3  08b1bd85c3efc2d7aa556fd79b073382  2019-10-29 16:16:52 +0000   \n",
              "4  3ac3f213732512d1d11bb73ab3b1900f  2019-10-31 09:32:06 +0000   \n",
              "5  f89b246d4e27c11623dbc7742523f319  2019-10-30 19:14:20 +0000   \n",
              "6  ddb01f73b53ea264c0a9fcc31b1dbd72  2019-10-30 07:46:44 +0000   \n",
              "7  516c5986d5dc20efaa37a58cbdea755a  2019-10-31 07:16:31 +0000   \n",
              "8  fc4d5d08dcad5e10f3408e89990065a0  2019-10-28 16:33:56 +0000   \n",
              "9  306bc2d444aa62cd53eb46fdbfd5c6f5  2019-10-28 16:57:50 +0000   \n",
              "\n",
              "                  Category                                      Product Title  \\\n",
              "0                Skin Care   Lee posh Lactic Acid 60% Anti ageing Pigmenta...   \n",
              "1                Skin Care   Branded SLB Works New 1.5mm Titanium 1200 nee...   \n",
              "2                Skin Care   Generic 1 Pc brand snail eye cream remove dar...   \n",
              "3                Skin Care   Generic Anti Snoring Snore Stopper Sleep Apne...   \n",
              "4  Grocery & Gourmet Foods   Harveys Crunchy & Creame Gourmet Delicacies C...   \n",
              "5                Skin Care   Shikai Borage Dry Skin Therapy Foot Cream, 4....   \n",
              "6            Bath & Shower                      Black & Tan Beer Soap 4-Pack    \n",
              "7            Bath & Shower   Mydio 2 Pack Waterproof Women Shower Caps Bat...   \n",
              "8  Grocery & Gourmet Foods   Food Studio Premium Quality in Shell Pistachi...   \n",
              "9  Grocery & Gourmet Foods   Dr Glutens Gluten Free Khracker (KHAKHRA) - 2...   \n",
              "\n",
              "                                 Product Description  \\\n",
              "0  PROFESSIONAL GRADE Face Peel: this peel stimul...   \n",
              "1  Item name: 1.5mm titanium 1200 needles microne...   \n",
              "2  Use: eye, item type: cream, net wt: 20g, gzzz:...   \n",
              "3  Prevent the tongue from dropping backward or b...   \n",
              "4     Harvey's wafer Cream Wafer 110g. Made in India   \n",
              "5  Package Quantity:3 Contains borage oil, clinic...   \n",
              "6  Our handmade soaps are made with the highest g...   \n",
              "7  Mydio 2 Pack Waterproof Women Shower Caps Bath...   \n",
              "8  Pistachios are small in appearance and are enc...   \n",
              "9  GLUTEN FREE KHAKHRAS. LIGHT HEALTHY AND ROASTE...   \n",
              "\n",
              "                           Brand Pack Size Or Quantity     Mrp    Price  \\\n",
              "0                       Lee Posh                  None  2000.0   799.00   \n",
              "1                      SLB Works                  None  2040.0  2040.00   \n",
              "2                        Generic                  None  1824.0  1042.00   \n",
              "3                        Generic                  None  2185.0  1399.00   \n",
              "4                        Harveys                  None   594.0   570.00   \n",
              "5                         ShiKai                 354 g  5344.0  5344.00   \n",
              "6  Lather+%26+Fizz+Bath+Boutique                  None  9086.0  7269.00   \n",
              "7                          Mydio                49.9 g  1659.0  1659.00   \n",
              "8                     FOODSTUDIO             399 Grams   760.0   660.00   \n",
              "9                      Dr Gluten                  None   279.0   279.00   \n",
              "\n",
              "   Site Name  Offers Combo Offers Stock Availibility Product Asin  \\\n",
              "0  Amazon In  60.05%         None                YES   B072BGHNJ1   \n",
              "1  Amazon In      0%         None                YES   B07QDTZYSJ   \n",
              "2  Amazon In  42.87%         None                YES   B07DCSN8MP   \n",
              "3  Amazon In  35.97%         None                YES   B07GLW9VQN   \n",
              "4  Amazon In   4.04%         None                YES   B07NFYYLF1   \n",
              "5  Amazon In      0%         None                YES   B001ET7E8C   \n",
              "6  Amazon In   20.0%         None                YES   B06XSRZV65   \n",
              "7  Amazon In      0%         None                YES   B074FVJN7D   \n",
              "8  Amazon In  13.16%         None                YES   B07Y3PTX42   \n",
              "9  Amazon In      0%         None                YES   B07Y4SSRR1   \n",
              "\n",
              "                                          Image Urls  \n",
              "0  https://images-na.ssl-images-amazon.com/images...  \n",
              "1  https://images-na.ssl-images-amazon.com/images...  \n",
              "2  https://images-na.ssl-images-amazon.com/images...  \n",
              "3  https://images-na.ssl-images-amazon.com/images...  \n",
              "4  https://images-na.ssl-images-amazon.com/images...  \n",
              "5  https://images-na.ssl-images-amazon.com/images...  \n",
              "6  https://images-na.ssl-images-amazon.com/images...  \n",
              "7  https://images-na.ssl-images-amazon.com/images...  \n",
              "8  https://images-na.ssl-images-amazon.com/images...  \n",
              "9  https://images-na.ssl-images-amazon.com/images...  "
            ],
            "text/html": [
              "\n",
              "  <div id=\"df-cda6878d-b6b2-4ce9-8454-abf38317e5b8\" class=\"colab-df-container\">\n",
              "    <div>\n",
              "<style scoped>\n",
              "    .dataframe tbody tr th:only-of-type {\n",
              "        vertical-align: middle;\n",
              "    }\n",
              "\n",
              "    .dataframe tbody tr th {\n",
              "        vertical-align: top;\n",
              "    }\n",
              "\n",
              "    .dataframe thead th {\n",
              "        text-align: right;\n",
              "    }\n",
              "</style>\n",
              "<table border=\"1\" class=\"dataframe\">\n",
              "  <thead>\n",
              "    <tr style=\"text-align: right;\">\n",
              "      <th></th>\n",
              "      <th>Uniq Id</th>\n",
              "      <th>Crawl Timestamp</th>\n",
              "      <th>Category</th>\n",
              "      <th>Product Title</th>\n",
              "      <th>Product Description</th>\n",
              "      <th>Brand</th>\n",
              "      <th>Pack Size Or Quantity</th>\n",
              "      <th>Mrp</th>\n",
              "      <th>Price</th>\n",
              "      <th>Site Name</th>\n",
              "      <th>Offers</th>\n",
              "      <th>Combo Offers</th>\n",
              "      <th>Stock Availibility</th>\n",
              "      <th>Product Asin</th>\n",
              "      <th>Image Urls</th>\n",
              "    </tr>\n",
              "  </thead>\n",
              "  <tbody>\n",
              "    <tr>\n",
              "      <th>0</th>\n",
              "      <td>eb49cc038190f6f03c272f79fbbce894</td>\n",
              "      <td>2019-10-30 11:38:11 +0000</td>\n",
              "      <td>Skin Care</td>\n",
              "      <td>Lee posh Lactic Acid 60% Anti ageing Pigmenta...</td>\n",
              "      <td>PROFESSIONAL GRADE Face Peel: this peel stimul...</td>\n",
              "      <td>Lee Posh</td>\n",
              "      <td>None</td>\n",
              "      <td>2000.0</td>\n",
              "      <td>799.00</td>\n",
              "      <td>Amazon In</td>\n",
              "      <td>60.05%</td>\n",
              "      <td>None</td>\n",
              "      <td>YES</td>\n",
              "      <td>B072BGHNJ1</td>\n",
              "      <td>https://images-na.ssl-images-amazon.com/images...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>1</th>\n",
              "      <td>1657cc30c438affede6a5060d6847363</td>\n",
              "      <td>2019-10-31 15:46:54 +0000</td>\n",
              "      <td>Skin Care</td>\n",
              "      <td>Branded SLB Works New 1.5mm Titanium 1200 nee...</td>\n",
              "      <td>Item name: 1.5mm titanium 1200 needles microne...</td>\n",
              "      <td>SLB Works</td>\n",
              "      <td>None</td>\n",
              "      <td>2040.0</td>\n",
              "      <td>2040.00</td>\n",
              "      <td>Amazon In</td>\n",
              "      <td>0%</td>\n",
              "      <td>None</td>\n",
              "      <td>YES</td>\n",
              "      <td>B07QDTZYSJ</td>\n",
              "      <td>https://images-na.ssl-images-amazon.com/images...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>2</th>\n",
              "      <td>41654633cce38c8650690f6dbac01fd3</td>\n",
              "      <td>2019-10-30 09:53:23 +0000</td>\n",
              "      <td>Skin Care</td>\n",
              "      <td>Generic 1 Pc brand snail eye cream remove dar...</td>\n",
              "      <td>Use: eye, item type: cream, net wt: 20g, gzzz:...</td>\n",
              "      <td>Generic</td>\n",
              "      <td>None</td>\n",
              "      <td>1824.0</td>\n",
              "      <td>1042.00</td>\n",
              "      <td>Amazon In</td>\n",
              "      <td>42.87%</td>\n",
              "      <td>None</td>\n",
              "      <td>YES</td>\n",
              "      <td>B07DCSN8MP</td>\n",
              "      <td>https://images-na.ssl-images-amazon.com/images...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>3</th>\n",
              "      <td>08b1bd85c3efc2d7aa556fd79b073382</td>\n",
              "      <td>2019-10-29 16:16:52 +0000</td>\n",
              "      <td>Skin Care</td>\n",
              "      <td>Generic Anti Snoring Snore Stopper Sleep Apne...</td>\n",
              "      <td>Prevent the tongue from dropping backward or b...</td>\n",
              "      <td>Generic</td>\n",
              "      <td>None</td>\n",
              "      <td>2185.0</td>\n",
              "      <td>1399.00</td>\n",
              "      <td>Amazon In</td>\n",
              "      <td>35.97%</td>\n",
              "      <td>None</td>\n",
              "      <td>YES</td>\n",
              "      <td>B07GLW9VQN</td>\n",
              "      <td>https://images-na.ssl-images-amazon.com/images...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>4</th>\n",
              "      <td>3ac3f213732512d1d11bb73ab3b1900f</td>\n",
              "      <td>2019-10-31 09:32:06 +0000</td>\n",
              "      <td>Grocery &amp; Gourmet Foods</td>\n",
              "      <td>Harveys Crunchy &amp; Creame Gourmet Delicacies C...</td>\n",
              "      <td>Harvey's wafer Cream Wafer 110g. Made in India</td>\n",
              "      <td>Harveys</td>\n",
              "      <td>None</td>\n",
              "      <td>594.0</td>\n",
              "      <td>570.00</td>\n",
              "      <td>Amazon In</td>\n",
              "      <td>4.04%</td>\n",
              "      <td>None</td>\n",
              "      <td>YES</td>\n",
              "      <td>B07NFYYLF1</td>\n",
              "      <td>https://images-na.ssl-images-amazon.com/images...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>5</th>\n",
              "      <td>f89b246d4e27c11623dbc7742523f319</td>\n",
              "      <td>2019-10-30 19:14:20 +0000</td>\n",
              "      <td>Skin Care</td>\n",
              "      <td>Shikai Borage Dry Skin Therapy Foot Cream, 4....</td>\n",
              "      <td>Package Quantity:3 Contains borage oil, clinic...</td>\n",
              "      <td>ShiKai</td>\n",
              "      <td>354 g</td>\n",
              "      <td>5344.0</td>\n",
              "      <td>5344.00</td>\n",
              "      <td>Amazon In</td>\n",
              "      <td>0%</td>\n",
              "      <td>None</td>\n",
              "      <td>YES</td>\n",
              "      <td>B001ET7E8C</td>\n",
              "      <td>https://images-na.ssl-images-amazon.com/images...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>6</th>\n",
              "      <td>ddb01f73b53ea264c0a9fcc31b1dbd72</td>\n",
              "      <td>2019-10-30 07:46:44 +0000</td>\n",
              "      <td>Bath &amp; Shower</td>\n",
              "      <td>Black &amp; Tan Beer Soap 4-Pack</td>\n",
              "      <td>Our handmade soaps are made with the highest g...</td>\n",
              "      <td>Lather+%26+Fizz+Bath+Boutique</td>\n",
              "      <td>None</td>\n",
              "      <td>9086.0</td>\n",
              "      <td>7269.00</td>\n",
              "      <td>Amazon In</td>\n",
              "      <td>20.0%</td>\n",
              "      <td>None</td>\n",
              "      <td>YES</td>\n",
              "      <td>B06XSRZV65</td>\n",
              "      <td>https://images-na.ssl-images-amazon.com/images...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>7</th>\n",
              "      <td>516c5986d5dc20efaa37a58cbdea755a</td>\n",
              "      <td>2019-10-31 07:16:31 +0000</td>\n",
              "      <td>Bath &amp; Shower</td>\n",
              "      <td>Mydio 2 Pack Waterproof Women Shower Caps Bat...</td>\n",
              "      <td>Mydio 2 Pack Waterproof Women Shower Caps Bath...</td>\n",
              "      <td>Mydio</td>\n",
              "      <td>49.9 g</td>\n",
              "      <td>1659.0</td>\n",
              "      <td>1659.00</td>\n",
              "      <td>Amazon In</td>\n",
              "      <td>0%</td>\n",
              "      <td>None</td>\n",
              "      <td>YES</td>\n",
              "      <td>B074FVJN7D</td>\n",
              "      <td>https://images-na.ssl-images-amazon.com/images...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>8</th>\n",
              "      <td>fc4d5d08dcad5e10f3408e89990065a0</td>\n",
              "      <td>2019-10-28 16:33:56 +0000</td>\n",
              "      <td>Grocery &amp; Gourmet Foods</td>\n",
              "      <td>Food Studio Premium Quality in Shell Pistachi...</td>\n",
              "      <td>Pistachios are small in appearance and are enc...</td>\n",
              "      <td>FOODSTUDIO</td>\n",
              "      <td>399 Grams</td>\n",
              "      <td>760.0</td>\n",
              "      <td>660.00</td>\n",
              "      <td>Amazon In</td>\n",
              "      <td>13.16%</td>\n",
              "      <td>None</td>\n",
              "      <td>YES</td>\n",
              "      <td>B07Y3PTX42</td>\n",
              "      <td>https://images-na.ssl-images-amazon.com/images...</td>\n",
              "    </tr>\n",
              "    <tr>\n",
              "      <th>9</th>\n",
              "      <td>306bc2d444aa62cd53eb46fdbfd5c6f5</td>\n",
              "      <td>2019-10-28 16:57:50 +0000</td>\n",
              "      <td>Grocery &amp; Gourmet Foods</td>\n",
              "      <td>Dr Glutens Gluten Free Khracker (KHAKHRA) - 2...</td>\n",
              "      <td>GLUTEN FREE KHAKHRAS. LIGHT HEALTHY AND ROASTE...</td>\n",
              "      <td>Dr Gluten</td>\n",
              "      <td>None</td>\n",
              "      <td>279.0</td>\n",
              "      <td>279.00</td>\n",
              "      <td>Amazon In</td>\n",
              "      <td>0%</td>\n",
              "      <td>None</td>\n",
              "      <td>YES</td>\n",
              "      <td>B07Y4SSRR1</td>\n",
              "      <td>https://images-na.ssl-images-amazon.com/images...</td>\n",
              "    </tr>\n",
              "  </tbody>\n",
              "</table>\n",
              "</div>\n",
              "    <div class=\"colab-df-buttons\">\n",
              "\n",
              "  <div class=\"colab-df-container\">\n",
              "    <button class=\"colab-df-convert\" onclick=\"convertToInteractive('df-cda6878d-b6b2-4ce9-8454-abf38317e5b8')\"\n",
              "            title=\"Convert this dataframe to an interactive table.\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "  <svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\" viewBox=\"0 -960 960 960\">\n",
              "    <path d=\"M120-120v-720h720v720H120Zm60-500h600v-160H180v160Zm220 220h160v-160H400v160Zm0 220h160v-160H400v160ZM180-400h160v-160H180v160Zm440 0h160v-160H620v160ZM180-180h160v-160H180v160Zm440 0h160v-160H620v160Z\"/>\n",
              "  </svg>\n",
              "    </button>\n",
              "\n",
              "  <style>\n",
              "    .colab-df-container {\n",
              "      display:flex;\n",
              "      gap: 12px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert {\n",
              "      background-color: #E8F0FE;\n",
              "      border: none;\n",
              "      border-radius: 50%;\n",
              "      cursor: pointer;\n",
              "      display: none;\n",
              "      fill: #1967D2;\n",
              "      height: 32px;\n",
              "      padding: 0 0 0 0;\n",
              "      width: 32px;\n",
              "    }\n",
              "\n",
              "    .colab-df-convert:hover {\n",
              "      background-color: #E2EBFA;\n",
              "      box-shadow: 0px 1px 2px rgba(60, 64, 67, 0.3), 0px 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "      fill: #174EA6;\n",
              "    }\n",
              "\n",
              "    .colab-df-buttons div {\n",
              "      margin-bottom: 4px;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert {\n",
              "      background-color: #3B4455;\n",
              "      fill: #D2E3FC;\n",
              "    }\n",
              "\n",
              "    [theme=dark] .colab-df-convert:hover {\n",
              "      background-color: #434B5C;\n",
              "      box-shadow: 0px 1px 3px 1px rgba(0, 0, 0, 0.15);\n",
              "      filter: drop-shadow(0px 1px 2px rgba(0, 0, 0, 0.3));\n",
              "      fill: #FFFFFF;\n",
              "    }\n",
              "  </style>\n",
              "\n",
              "    <script>\n",
              "      const buttonEl =\n",
              "        document.querySelector('#df-cda6878d-b6b2-4ce9-8454-abf38317e5b8 button.colab-df-convert');\n",
              "      buttonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "\n",
              "      async function convertToInteractive(key) {\n",
              "        const element = document.querySelector('#df-cda6878d-b6b2-4ce9-8454-abf38317e5b8');\n",
              "        const dataTable =\n",
              "          await google.colab.kernel.invokeFunction('convertToInteractive',\n",
              "                                                    [key], {});\n",
              "        if (!dataTable) return;\n",
              "\n",
              "        const docLinkHtml = 'Like what you see? Visit the ' +\n",
              "          '<a target=\"_blank\" href=https://colab.research.google.com/notebooks/data_table.ipynb>data table notebook</a>'\n",
              "          + ' to learn more about interactive tables.';\n",
              "        element.innerHTML = '';\n",
              "        dataTable['output_type'] = 'display_data';\n",
              "        await google.colab.output.renderOutput(dataTable, element);\n",
              "        const docLink = document.createElement('div');\n",
              "        docLink.innerHTML = docLinkHtml;\n",
              "        element.appendChild(docLink);\n",
              "      }\n",
              "    </script>\n",
              "  </div>\n",
              "\n",
              "\n",
              "<div id=\"df-7ef0b32d-776f-48d2-be69-9f0ab4edcf48\">\n",
              "  <button class=\"colab-df-quickchart\" onclick=\"quickchart('df-7ef0b32d-776f-48d2-be69-9f0ab4edcf48')\"\n",
              "            title=\"Suggest charts\"\n",
              "            style=\"display:none;\">\n",
              "\n",
              "<svg xmlns=\"http://www.w3.org/2000/svg\" height=\"24px\"viewBox=\"0 0 24 24\"\n",
              "     width=\"24px\">\n",
              "    <g>\n",
              "        <path d=\"M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zM9 17H7v-7h2v7zm4 0h-2V7h2v10zm4 0h-2v-4h2v4z\"/>\n",
              "    </g>\n",
              "</svg>\n",
              "  </button>\n",
              "\n",
              "<style>\n",
              "  .colab-df-quickchart {\n",
              "      --bg-color: #E8F0FE;\n",
              "      --fill-color: #1967D2;\n",
              "      --hover-bg-color: #E2EBFA;\n",
              "      --hover-fill-color: #174EA6;\n",
              "      --disabled-fill-color: #AAA;\n",
              "      --disabled-bg-color: #DDD;\n",
              "  }\n",
              "\n",
              "  [theme=dark] .colab-df-quickchart {\n",
              "      --bg-color: #3B4455;\n",
              "      --fill-color: #D2E3FC;\n",
              "      --hover-bg-color: #434B5C;\n",
              "      --hover-fill-color: #FFFFFF;\n",
              "      --disabled-bg-color: #3B4455;\n",
              "      --disabled-fill-color: #666;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart {\n",
              "    background-color: var(--bg-color);\n",
              "    border: none;\n",
              "    border-radius: 50%;\n",
              "    cursor: pointer;\n",
              "    display: none;\n",
              "    fill: var(--fill-color);\n",
              "    height: 32px;\n",
              "    padding: 0;\n",
              "    width: 32px;\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart:hover {\n",
              "    background-color: var(--hover-bg-color);\n",
              "    box-shadow: 0 1px 2px rgba(60, 64, 67, 0.3), 0 1px 3px 1px rgba(60, 64, 67, 0.15);\n",
              "    fill: var(--button-hover-fill-color);\n",
              "  }\n",
              "\n",
              "  .colab-df-quickchart-complete:disabled,\n",
              "  .colab-df-quickchart-complete:disabled:hover {\n",
              "    background-color: var(--disabled-bg-color);\n",
              "    fill: var(--disabled-fill-color);\n",
              "    box-shadow: none;\n",
              "  }\n",
              "\n",
              "  .colab-df-spinner {\n",
              "    border: 2px solid var(--fill-color);\n",
              "    border-color: transparent;\n",
              "    border-bottom-color: var(--fill-color);\n",
              "    animation:\n",
              "      spin 1s steps(1) infinite;\n",
              "  }\n",
              "\n",
              "  @keyframes spin {\n",
              "    0% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "      border-left-color: var(--fill-color);\n",
              "    }\n",
              "    20% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    30% {\n",
              "      border-color: transparent;\n",
              "      border-left-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    40% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-top-color: var(--fill-color);\n",
              "    }\n",
              "    60% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "    }\n",
              "    80% {\n",
              "      border-color: transparent;\n",
              "      border-right-color: var(--fill-color);\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "    90% {\n",
              "      border-color: transparent;\n",
              "      border-bottom-color: var(--fill-color);\n",
              "    }\n",
              "  }\n",
              "</style>\n",
              "\n",
              "  <script>\n",
              "    async function quickchart(key) {\n",
              "      const quickchartButtonEl =\n",
              "        document.querySelector('#' + key + ' button');\n",
              "      quickchartButtonEl.disabled = true;  // To prevent multiple clicks.\n",
              "      quickchartButtonEl.classList.add('colab-df-spinner');\n",
              "      try {\n",
              "        const charts = await google.colab.kernel.invokeFunction(\n",
              "            'suggestCharts', [key], {});\n",
              "      } catch (error) {\n",
              "        console.error('Error during call to suggestCharts:', error);\n",
              "      }\n",
              "      quickchartButtonEl.classList.remove('colab-df-spinner');\n",
              "      quickchartButtonEl.classList.add('colab-df-quickchart-complete');\n",
              "    }\n",
              "    (() => {\n",
              "      let quickchartButtonEl =\n",
              "        document.querySelector('#df-7ef0b32d-776f-48d2-be69-9f0ab4edcf48 button');\n",
              "      quickchartButtonEl.style.display =\n",
              "        google.colab.kernel.accessAllowed ? 'block' : 'none';\n",
              "    })();\n",
              "  </script>\n",
              "</div>\n",
              "\n",
              "    </div>\n",
              "  </div>\n"
            ],
            "application/vnd.google.colaboratory.intrinsic+json": {
              "type": "dataframe",
              "variable_name": "df",
              "summary": "{\n  \"name\": \"df\",\n  \"rows\": 29301,\n  \"fields\": [\n    {\n      \"column\": \"Uniq Id\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 29301,\n        \"samples\": [\n          \"1f70c3178c7c87aa6ea19dc418101e52\",\n          \"a202cf24cdc30ddc016818f42191eb41\",\n          \"494a4c84f0f5d4c7c6b1683fa78a4bc6\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Crawl Timestamp\",\n      \"properties\": {\n        \"dtype\": \"object\",\n        \"num_unique_values\": 27280,\n        \"samples\": [\n          \"2019-10-29 15:55:30 +0000\",\n          \"2019-10-31 10:37:14 +0000\",\n          \"2019-10-31 10:53:04 +0000\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Category\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 6,\n        \"samples\": [\n          \"Skin Care\",\n          \"Grocery & Gourmet Foods\",\n          \"Detergents & Dishwash\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Product Title\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 28943,\n        \"samples\": [\n          \" Hydra Sensitive Face Serum 50ml \",\n          \" Simple Kind to Skin Smoothing Facial Scrub, 5 oz (Quantity. \",\n          \" Cadbury Dairy Milk Chocolate Home Treats, 126g - Pack of 4 \"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Product Description\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 22014,\n        \"samples\": [\n          \"Greaseless, ultra moisturizing botanical blend, including rich lipids, vegetable and plant proteins, and Vitamin B5, gently cleanses, nourishes and hydrates hair to help resist breakage. Color stays brilliant and lasts. Leaves hair silky-smooth, shiny, manageable and deeply hydrated.\",\n          \"Item Type: Nail Polish ,Model Number: fur color nail polish gel PC01-12. , .Package include: 1 Piece\",\n          \"A concentrated pore refining facial serum Highly concentrated with Houttuynia Cordata extract to normalize sebum production Balances skin's oil & water content Refines skin texture & reduces enlarged pores Unveils a smoother & porcelainlike complexion Ideal for combination to oily skin types Dermatologisttested To use: After cleansing & toning, take a few drops on palms & rub together to warm the serum. Pat palms on face until serum is fully absorbed. Follow with cream or moisturizer\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Brand\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 8373,\n        \"samples\": [\n          \"VALAMJI\",\n          \"The Blue Ingredient\",\n          \"WEAVE AIDE\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Pack Size Or Quantity\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 452,\n        \"samples\": [\n          \"953 g\",\n          \"426 Grams\",\n          \"100 Kg\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Mrp\",\n      \"properties\": {\n        \"dtype\": \"number\",\n        \"std\": 3092.921340006886,\n        \"min\": 12.0,\n        \"max\": 80000.0,\n        \"num_unique_values\": 6323,\n        \"samples\": [\n          7735.0,\n          1694.0,\n          4349.0\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Price\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 6293,\n        \"samples\": [\n          \"820.00\",\n          \"5224.00\",\n          \"5081.00\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Site Name\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 1,\n        \"samples\": [\n          \"Amazon In\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Offers\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 4338,\n        \"samples\": [\n          \"73.97%\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Combo Offers\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 35,\n        \"samples\": [\n          \" QYF Buy1 Get 1Gift Hyaluronic Acid Serum Acne Treatment Moisturizing Anti Wrinkles \"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Stock Availibility\",\n      \"properties\": {\n        \"dtype\": \"category\",\n        \"num_unique_values\": 2,\n        \"samples\": [\n          \"NO\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Product Asin\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 29301,\n        \"samples\": [\n          \"B07D24CT5L\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    },\n    {\n      \"column\": \"Image Urls\",\n      \"properties\": {\n        \"dtype\": \"string\",\n        \"num_unique_values\": 28893,\n        \"samples\": [\n          \"https://images-na.ssl-images-amazon.com/images/I/41WHXp9enfL._AC_US40_.jpg|https://images-na.ssl-images-amazon.com/images/G/01/x-locale/common/transparent-pixel._V192234675_.gif\"\n        ],\n        \"semantic_type\": \"\",\n        \"description\": \"\"\n      }\n    }\n  ]\n}"
            }
          },
          "metadata": {},
          "execution_count": 93
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "df.columns"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "_wnl8f7bOu-Y",
        "outputId": "6cb6652c-bd7b-490c-e124-13fba8b65a30"
      },
      "execution_count": 6,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "Index(['Uniq Id', 'Crawl Timestamp', 'Category', 'Product Title',\n",
              "       'Product Description', 'Brand', 'Pack Size Or Quantity', 'Mrp', 'Price',\n",
              "       'Site Name', 'Offers', 'Combo Offers', 'Stock Availibility',\n",
              "       'Product Asin', 'Image Urls'],\n",
              "      dtype='object')"
            ]
          },
          "metadata": {},
          "execution_count": 6
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "#Curate the dataset\n",
        "\n",
        "items = []\n",
        "for datapoint in df:\n",
        "    try:\n",
        "        price = float(datapoint[\"Mrp\"])\n",
        "        if price > 0:\n",
        "            item = Item(datapoint, price)\n",
        "            if item.include:\n",
        "                items.append(item)\n",
        "    except ValueError as e:\n",
        "        pass\n",
        "\n",
        "print(f\"There are {len(items):,} items\")"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 251
        },
        "id": "l0x0farUidmR",
        "outputId": "9ddac4e5-f3ab-4e11-8c18-99e217a1fae0"
      },
      "execution_count": 92,
      "outputs": [
        {
          "output_type": "error",
          "ename": "TypeError",
          "evalue": "string indices must be integers",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
            "\u001b[0;32m<ipython-input-92-fc88f5a81c49>\u001b[0m in \u001b[0;36m<cell line: 4>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;32mfor\u001b[0m \u001b[0mdatapoint\u001b[0m \u001b[0;32min\u001b[0m \u001b[0mdf\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m     \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 6\u001b[0;31m         \u001b[0mprice\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mfloat\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdatapoint\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"Mrp\"\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      7\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mprice\u001b[0m \u001b[0;34m>\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      8\u001b[0m             \u001b[0mitem\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mItem\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mdatapoint\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mprice\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;31mTypeError\u001b[0m: string indices must be integers"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "EMuBY0fM2RDo"
      },
      "outputs": [],
      "source": [
        "BASE_MODEL = \"meta-llama/Meta-Llama-3.1-8B\""
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "id": "PD9MMeBJ2XSj"
      },
      "outputs": [],
      "source": [
        "MIN_TOKENS = 150\n",
        "MAX_TOKENS = 160\n",
        "\n",
        "MIN_CHARS = 300\n",
        "CEILING_CHARS = MAX_TOKENS * 7"
      ]
    }
  ],
  "metadata": {
    "colab": {
      "provenance": [],
      "authorship_tag": "ABX9TyP65CN+kJIE0qsXm+a/g0rA",
      "include_colab_link": true
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}